name: TWERK/B2B
favicon: null
layout_spectrum: 0.4378579743206501
typography_spectrum: 0.5083679016679525
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#cc9900'
    - '#ffde00'
    - '#000066'
    - '#006666'
    - '#ffffff'
  brandStrength: 0.875
  lightness: 0.8125
  saturation: 0.5625
  rhythmicContrast: 0.5
purpose: []
